version: "3.2"

services:

  postgres:
    image: postgres:15
    container_name: hmpps-integration-events-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - hmpps
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 30s
      timeout: 10s
      retries: 5

  localstack:
    image: localstack/localstack:3.0
    container_name: localstack-events
    networks:
      - hmpps
    ports:
      - 4566:4566
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./scripts/localstack}:/etc/localstack"
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
    environment:
      - SERVICES=sqs,sns,s3,secretsmanager
      - DEFAULT_REGION=eu-west-2
    healthcheck:
      test: 'curl localhost:4566/_localstack/init | grep -q ''"READY": true'''
      interval: 60s
      timeout: 2s
      retries: 10

networks:
  hmpps:
