version: "3.2"

services:
  hmpps-integration-events:
    build:
      context: .
    network_mode: "host"
    container_name: hmpps-integration-events
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=localstack
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=TRACE

  postgres:
    image: postgres:14-alpine
    container_name: hmpps-integration-events-db
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=pa55word
      - POSTGRES_USER=postgres
      - POSTGRES_DB=event_store
    networks:
      - hmpps
    tmpfs:
      - /var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 30s
      timeout: 10s
      retries: 5

  localstack:
    image: localstack/localstack:3.0
    container_name: local-stack-aws
    networks:
      - hmpps
    ports:
      - 4566:4566
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
    environment:
      - SERVICES=sqs,sns
      - DEFAULT_REGION=eu-west-2
    healthcheck:
      test: 'curl localhost:4566/_localstack/init'
      interval: 60s
      timeout: 2s
      retries: 10

networks:
  hmpps:
