spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/event_store
    username: postgres
    password: pa55word
  flyway:
    enabled: true
    baselineOnMigrate: true

aws:
  provider: localstack

hmpps.sqs:
  provider: localstack
  localstackUrl: http://localhost:4566
  topics:
    integrationeventtopic:
      arn: arn:aws:sns:eu-west-2:000000000000:integration-event-topic