spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/event_store?sslmode=prefer
    username: postgres
    password: pa55word
  flyway:
    enabled: true
    baselineOnMigrate: true

services:
  integration-api:
    url: https://dev.integration-api.hmpps.service.justice.gov.uk
#    ADD api key from namespace secret
    apikey: ""
    certificate-bucket-name: "certificate-backup"
    certificate-password: "client"
    certificate-path: "testclient/client.p12"

aws:
  provider: localstack
  region: eu-west-2

hmpps.sqs:
  provider: localstack
  localstackUrl: http://localhost:4566
  useWebToken: false
  queues:
    hmppsdomainqueue:
      queueName: hmpps_integrations_events_queue
      queueArn: arn:aws:sns:eu-west-2:000000000000:hmpps_integrations_events_queue
      dlqName: hmpps_integrations_events_queue_dlq
      subscribeTopicId: domainevents
    mappssubscriberqueue:
      queueName: mapps_subscriber_queue
      dlqName: mapps_subscriber_queue_dlq
      subscribeTopicId: integrationeventtopic
    audit:
      queueName: "audit"

  topics:
    domainevents:
      arn: arn:aws:sns:eu-west-2:000000000000:hmpps_domain_events
    integrationeventtopic:
      arn: arn:aws:sns:eu-west-2:000000000000:integration-event-topic

hmpps.secret:
  provider: localstack
  localstackUrl: http://localhost:4566
  secrets:
    mapps-client-org:
      secretId: testSecret
      queueId: mappssubscriberqueue


hmpps.s3:
  provider: localstack
  localstackUrl: http://localhost:4566
  buckets:
    certificate-backup:
      bucketName: certificate-backup
