spring:

  jpa:
    show-sql: true
  flyway:
    enabled: true
    baselineOnMigrate: true

services:
  integrations-api:
    url: https://dev.integration-api.hmpps.service.justice.gov.uk
    apikey: ""
    certificatebucketname: ""
    certificatepassword: ""
    certificatepath: ""

aws:
  provider: localstack
  region: eu-west-2



hmpps.sqs:
  provider: localstack
  localstackUrl: http://localhost:4566
  useWebToken: false
  queues:
    hmppsdomainqueue:
      queueName: hmpps_integrations_events_queue
      queueArn: arn:aws:sns:eu-west-2:000000000000:hmpps_integrations_events_queue
      dlqName: hmpps_integrations_events_queue_dlq
      subscribeTopicId: domainevents
  topics:
    domainevents:
      arn: arn:aws:sns:eu-west-2:000000000000:hmpps_domain_events
    integrationeventtopic:
      arn: arn:aws:sns:eu-west-2:000000000000:integration-event-topic

hmpps.secret:
  provider: localstack
  localstackUrl: http://localhost:4566
  secrets:
    mapps-client-org:
      secretName: testSecret
      subscriberArn: "arn:aws:sns:eu-west-2:000000000000:integration-event-topic:717e006e-ab56-49d8-89f8-fc43568e242a"



