spring:
  flyway:
    enabled: true

aws:
  provider: localstack

hmpps.sqs:
  provider: localstack
  localstackUrl: http://localhost:4566
  topics:
    integrationeventtopic:
      arn: arn:aws:sns:eu-west-2:000000000000:integration-api-event-topic