hmpps.sqs:
  provider: localstack
  queues:
    prisoner:
      queueName: hmpps_integrations_events_queue
      queueArn: arn:aws:sns:eu-west-2:000000000000:hmpps_integrations_events_queue
      dlqName: hmpps_integrations_events_queue_dlq
      subscribeTopicId: domainevents
  topics:
    domainevents:
      arn: arn:aws:sns:eu-west-2:000000000000:hmpps_domain_events
