spring:

  jpa:
    show-sql: true

services:
  integrations-api:
    url: https://dev.integration-api.hmpps.service.justice.gov.uk
    apikey: "LIJGe1vhuo7FefAcG8Aii1Pi9QcOibE3Hy7MVsab"
    certificate-bucket-name: "certificate-backup"
    certificate-password: "client"
    certificate-path: "testclient/client.p12"

aws:
  provider: localstack
  region: eu-west-2



hmpps.sqs:
  provider: localstack
  localstackUrl: http://localhost:4566
  useWebToken: false
  queues:
    hmppsdomainqueue:
      queueName: hmpps_integrations_events_queue
      queueArn: arn:aws:sns:eu-west-2:000000000000:hmpps_integrations_events_queue
      dlqName: hmpps_integrations_events_queue_dlq
      subscribeTopicId: domainevents
  topics:
    domainevents:
      arn: arn:aws:sns:eu-west-2:000000000000:hmpps_domain_events
    integrationeventtopic:
      arn: arn:aws:sns:eu-west-2:000000000000:integration-event-topic

hmpps.secret:
  provider: localstack
  localstackUrl: http://localhost:4566
  secrets:
    mapps-client-org:
      secretId: testSecret
      queueName: arn:aws:sns:eu-west-2:000000000000:integration-event-topic:717e006e-ab56-49d8-89f8-fc43568e242a


hmpps.s3:
  provider: localstack
  localstackUrl: http://localhost:4566
  buckets:
    certificate-backup:
      bucketName: certificate-backup
