---
# Per environment values which override defaults in hmpps-integration-events/values.yaml

generic-service:
  ingress:
    host: hmpps-integration-events.apps.live.cloud-platform.service.justice.gov.uk

  env:
    SERVICES_INTEGRATION-API_URL: https://integration-api.hmpps.service.justice.gov.uk
    HMPPS_AUTH_URL: https://sign-in.hmpps.service.justice.gov.uk
    PROBATION_INTEGRATION_API_URL: https://external-api-and-delius.hmpps.service.justice.gov.uk
    SENTRY_ENVIRONMENT: prod
    SPRING_PROFILES_ACTIVE: prod

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: PROD_ALERTS_SEVERITY_LABEL
