---
# Per environment values which override defaults in hmpps-integration-events/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: hmpps-integration-events-dev.apps.live.cloud-platform.service.justice.gov.uk
    annotations:
      nginx.ingress.kubernetes.io/auth-tls-secret: "hmpps-integration-api-dev/client-certificate-auth"
  env:
    SERVICES_INTEGRATION-API_URL: https://dev.integration-api.hmpps.service.justice.gov.uk
    HMPPS_AUTH_URL: https://sign-in-dev.hmpps.service.justice.gov.uk
    PROBATION_INTEGRATION_API_URL: https://external-api-and-delius-dev.hmpps.service.justice.gov.uk
    SPRING_PROFILES_ACTIVE: dev
    SENTRY_ENVIRONMENT: dev

#  namespace_secrets:
#    event-test-client-queue:
#      TEST_CLIENT_QUEUE_NAME: "sqs_name"
#      TEST_CLIENT_QUEUE_ARN: "sqs_arn"
# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: NON_PROD_ALERTS_SEVERITY_LABEL
