DROP TABLE IF EXISTS EVENT_NOTIFICATION;

CREATE TABLE EVENT_NOTIFICATION(
    EVENT_ID SERIAL PRIMARY KEY,
    HMPPS_ID varchar(15),
    EVENT_TYPE varchar(20),
    URL varchar(200),
    LAST_MODIFIED_DATETIME TIMESTAMP NOT NULL
);

COMMENT ON TABLE EVENT_NOTIFICATION IS 'Holds HMPPS event list in temporary store to reduce duplicate messages';

CREATE UNIQUE INDEX LAST_MODIFIED_DATETIME ON EVENT_NOTIFICATION (LAST_MODIFIED_DATETIME);

INSERT INTO EVENT_NOTIFICATION (EVENT_ID, HMPPS_ID, EVENT_TYPE, URL, LAST_MODIFIED_DATETIME)
VALUES (111,'Event past', 'ADDRESS_CHANGE', '', TIMESTAMP '2024-04-02 10:42:32.000000');