generic-service:
  nameOverride: hmpps-integration-events
  productId: "DPS071" # productId for the product that this belongs too, i.e. DPS001, see README.md for details

  replicaCount: 4

  image:
    repository: quay.io/hmpps/hmpps-integration-events
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-integration-events-cert

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    HMPPS_SQS_USE_WEB_TOKEN: "true"
    HMPPS_SECRET_SECRETS_MAPPS-CLIENT-ORG_QUEUE-NAME: "MAPPSQUEUE"
    HMPPS_SQS_QUEUES_MAPPSQUEUE_SUBSCRIBETOPICID: "INTEGRATIONEVENTTOPIC"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-integration-events:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
    certificate-store:
      SERVICE_INTEGRATIONS-API_CERTIFICATE-BUCKET-NAME: "bucket_name"
      SERVICE_INTEGRATIONS-API_CERTIFICATE-PASSWORD: "event_service_certificate_password"
      SERVICE_INTEGRATIONS-API_CERTIFICATE-PATH: "event_service_certificate_path"
      HMPPS_S3_BUCKETS_CERTIFICATE-BACKUP_BUCKET-NAME: "bucket_name"
    consumer-api-keys:
      SERVICE_INTEGRATION-API_APIKEY: "event-service"
    hmpps-integration-events-topic:
      HMPPS_SQS_TOPICS_INTEGRATIONEVENTTOPIC_ARN: "sns_arn"
    hmpps-integration-api-domain-events-sqs-instance-output:
      HMPPS_SQS_QUEUES_HMPPSDOMAINQUEUE_QUEUENAME: "sqs_name"
      HMPPS_SQS_QUEUES_HMPPSDOMAINQUEUE_QUEUEARN: "sqs_arn"
      HMPPS_SQS_TOPIC_DOMAINEVENTS_ARN: "hmpps-domain-events-topic-arn"
    hmpps-integration-api-domain-events-sqs-dl-instance-output:
      HMPPS_SQS_QUEUES_HMPPSDOMAINQUEUE_DLQNAME: "sqs_name"
    event_mapps_queue:
      HMPPS_SQS_QUEUES_MAPPSQUEUE_QUEUENAME: "sqs_name"
      HMPPS_SQS_QUEUES_MAPPSQUEUE_QUEUEARN: "sqs_arn"
      HMPPS_SECRET_SECRETS_MAPPS-CLIENT-ORG_SECRET-ID: "mapps_filter_policy_secret_id"
    rds-postgresql-instance-output:
      DB_SERVER: "rds_instance_address"
      DB_NAME: "database_name"
      DB_USER: "database_username"
      DB_PASS: "database_password"

  allowlist:
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: hmpps-integration-events
