generic-service:
  nameOverride: hmpps-integration-events
  serviceAccountName: hmpps-integration-event
  productId: "DPS071" # productId for the product that this belongs too, i.e. DPS001, see README.md for details

  replicaCount: 4

  image:
    repository: quay.io/hmpps/hmpps-integration-events
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-integration-events-cert

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-integration-events:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
    certificate-store:
      CERTIFICATE_BUCKET_NAME: "bucket_name"
      CERTIFICATE_PASSWORD: "event_service_certificate_password"
      CERTIFICATE_PATH: "event_service_certificate_path"
    consumer-api-keys:
      API_KEY: "event-service"
    hmpps-integration-events-topic:
      INTEGRATION_EVENT_TOPIC_ARN: "sns_arn"
    hmpps-integration-api-domain-events-sqs-instance-output:
      HMPPS_DOMAIN_QUEUE_NAME: "sqs_name"
      HMPPS_DOMAIN_QUEUE_ARN: "sqs_arn"
      HMPPS_DOMAIN_TOPIC_ARN: "hmpps_domain_events_topic_arn"
    hmpps-integration-api-domain-events-sqs-dl-instance-output:
      HMPPS_DOMAIN_DL_QUEUE_NAME: "sqs_name"
    event-mapps-queue:
      MAPPS_QUEUE_NAME: "sqs_name"
      MAPPS_QUEUE_ARN: "sqs_arn"
      MAPPS_FILTER_POLICY_SECRECT_ID: "mapps_filter_policy_secret_id"
    rds-postgresql-instance-output:
      DB_SERVER: "rds_instance_endpoint"
      DB_NAME: "database_name"
      DB_USER: "database_username"
      DB_PASS: "database_password"

  allowlist:
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: hmpps-integration-events
